# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_auto_20180107_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='key',
            field=models.CharField(default='', help_text='internal key of the attribute group', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
