# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_auto_20180108_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
