# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_attribute_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='orderable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='searchable',
            field=models.BooleanField(default=False),
        ),
    ]
