# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0007_auto_20180602_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attributes.Attribute'),
        ),
    ]
