# Generated by Django 2.1.3 on 2018-11-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0009_auto_20180809_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='max_length',
            field=models.PositiveIntegerField(help_text='Maximum length', null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='max_value',
            field=models.FloatField(help_text='Maximum value', null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='min_value',
            field=models.FloatField(help_text='Minimum value', null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='attributes.AttributeGroup'),
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='attribute',
            field=models.ForeignKey(limit_choices_to={'result_type__in': ['DropDown']}, on_delete=django.db.models.deletion.DO_NOTHING, to='attributes.Attribute'),
        ),
    ]
