# Generated by Django 2.1.8 on 2019-06-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0011_auto_20190425_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='min_length',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum length', null=True),
        ),
    ]
