# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('healthsites', '0020_auto_20160627_1038'),
    ]

    operations = [
        migrations.RunSQL('create schema if not exists core_utils;'),

        migrations.RunSQL("""
CREATE OR REPLACE FUNCTION core_utils.get_events(min_x double precision, min_y double precision, max_x double precision, max_y double precision)
  RETURNS text
STABLE
LANGUAGE SQL
AS $body$
SELECT
    coalesce(jsonb_agg(d.row)::TEXT, '[]') AS data
from
(
    select
        jsonb_build_object(
            'assessment', jsonb_object_agg(
                   ag_name || '/' || ac_name,
                   jsonb_build_object(
                   'option', '',
                   'value', r.value,
                   'description', ''
                   )
               ),
               'id', r.id,
               'created_date', r.created_date,
               'data_captor', r.email,
               'overall_assessment', r.overall_assessment,
               'name', r.name,
               'geometry', r.geometry,
               'enriched', r.enriched,
               'country', r.country
               ) AS row
    from
    (
        SELECT
            dg.name as ag_name,
            da.name as ac_name,
            case
                when da.result_type = 'Integer' then val_int::varchar
                when da.result_type = 'Decimal' then val_real::varchar
                when da.result_type = 'DropDown' then val_text::varchar
                when da.result_type = 'MultipleChoice' then val_text::varchar
                else null
            end as value,
            ft.id,
            chg.ts_created as created_date,
            wu.email,
            ft.overall_assessment,
            ft.name,
            ARRAY [ST_X(ft.point_geometry), ST_Y(ft.point_geometry)] as geometry,
            true as enriched,
            'Unknown'::text as country

        FROM
            data.feature_attribute_value fav
            JOIN data.feature ft
            ON fav.feature_id = ft.id AND
               ft.point_geometry && ST_SetSRID(ST_MakeBox2D(ST_Point($1, $2), ST_Point($3, $4)),4326)
            JOIN public.attributes_attribute da ON da.id = fav.attribute_id
            JOIN public.attributes_attributegroup dg ON dg.id = da.attribute_group_id
            JOIN data.changeset chg ON ft.changeset_id = chg.id
            JOIN webusers_webuser wu ON chg.webuser_id = wu.id
    order by id
    ) r

    group by
        r.id
        , r.created_date
        , r.email
        , r.overall_assessment
        , r.name
        , r.geometry
        , r.enriched
        , r.country
) d;
$body$;
            """),
    ]
