# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('healthsites', '0020_auto_20160627_1038'),
    ]

    operations = []
