# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 18:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('webuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_state', models.CharField(choices=[('u', 'Uploaded and analysed'), ('i', 'Inserted in database'), ('n', 'None')], default='n', max_length=2)),
                ('new_state', models.CharField(choices=[('u', 'Uploaded and analysed'), ('i', 'Inserted in database'), ('n', 'None')], max_length=2)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('warnings', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('report_dict', django.contrib.postgres.fields.jsonb.JSONField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imports.Task')),
                ('webuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
