# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='changeset_id',
            field=models.IntegerField(null=True),
        ),
    ]
