# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 18:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0002_load_country_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Please enter your email address. This will also be your login name.', max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(help_text='Your first name.', max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Your last name.', max_length=100, verbose_name='Last name')),
                ('phone_number', models.CharField(blank=True, help_text='This is optional. If entered alerts will be sent to this number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+6288888888888". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('notified', models.BooleanField(default=False, help_text='Check this box to receive SMS notifications.', verbose_name='Receive notifications?')),
                ('is_active', models.BooleanField(default=True, help_text="Unchecked this to disable this user's account without deleting it.", verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, help_text='Check this to make the user an admin.', verbose_name='Admin')),
                ('is_staff', models.BooleanField(default=False, help_text='Staff can access wk-admin page.', verbose_name='Staff')),
                ('is_data_captor', models.BooleanField(default=False, help_text='Data capturer can add events.', verbose_name='Data capturer')),
                ('north', models.FloatField(default=40, help_text='The northern boundary of the area of interest.', verbose_name='North')),
                ('east', models.FloatField(default=55, help_text='The eastern boundary of the area of interest.', verbose_name='East')),
                ('south', models.FloatField(default=24, help_text='The southern boundary of the area of interest.', verbose_name='South')),
                ('west', models.FloatField(default=28, help_text='The western boundary of the area of interest.', verbose_name='West')),
                ('key', models.CharField(default='0000000000000000000000000000000000000000', help_text='Account confirmation key as sent to the user by email.', max_length=40, verbose_name='Account confirmation key')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether this user has activated their account by email.', verbose_name='Confirmed')),
                ('notify_immediately', models.BooleanField(default=False, help_text='Check this to activate immediate notifications. If unchecked, the user will only be notified by nightly batch reports.', verbose_name='Notify immediately')),
                ('countries_notified', models.ManyToManyField(blank=True, help_text='Select one or more countries for which you wish to receive notifications.', to='country.Country', verbose_name='Countries of interest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
