# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webusers.models


class Migration(migrations.Migration):

    dependencies = [
        ('webusers', '0002_webuser_geofence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='woreda', max_length=32)),
                ('values', webusers.models.ChoiceArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None)),
                ('webuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='grant',
            unique_together=set([('webuser', 'key')]),
        ),
    ]
