# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webusers', '0003_auto_20180215_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='is_readonly',
            field=models.BooleanField(default=False, help_text='User can only read data', verbose_name='Readonly'),
        ),
    ]
