# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webusers', '0004_webuser_is_readonly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='is_readonly',
            field=models.BooleanField(default=False, help_text='User can see all data and export but cannot update data', verbose_name='Readonly'),
        ),
    ]
