# Generated by Django 2.1.8 on 2019-06-02 12:23

from django.db import migrations, connection


def populate_org_uuid(apps, schema_editor):

    with connection.cursor() as cur:
        cur.execute('update webusers_webuser set username=split_part(email, $$@$$, 1);')
        cur.execute('update webusers_webuser set email=$$readonly-sys@example.com$$, username=$$readonly-sys$$ where email=$$readonly@example.com$$;')

        cur.execute('update features.active_data set email= split_part(email, $$@$$, 1);')
        cur.execute('update features.deleted_data set email= split_part(email, $$@$$, 1);')
        cur.execute('update features.history_data set email= split_part(email, $$@$$, 1);')


class Migration(migrations.Migration):

    dependencies = [
        ('webusers', '0006_auto_20190602_1422'),
    ]

    operations = [
        migrations.RunPython(populate_org_uuid),
    ]
