# Generated by Django 2.1.8 on 2019-06-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webusers', '0008_auto_20190602_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Please enter your email address.', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
