# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_format', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_state', models.CharField(choices=[('u', 'Uploaded and analysed'), ('i', 'Inserted in database'), ('n', 'None')], default='n', max_length=2)),
                ('new_state', models.CharField(choices=[('u', 'Uploaded and analysed'), ('i', 'Inserted in database'), ('n', 'None')], max_length=2)),
                ('file_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_file.File')),
            ],
        ),
    ]
