# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_auto_20180807_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
