# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_auto_20180807_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='error_msgs',
        ),
        migrations.AddField(
            model_name='filehistory',
            name='error_msgs',
            field=models.TextField(default='A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='changed_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 7, 13, 1, 55, 513431, tzinfo=utc)),
        ),
    ]
