# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0007_auto_20180808_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehistory',
            name='changed_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 15, 26, 11, 489742, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='error_msgs',
            field=models.TextField(default='none'),
        ),
    ]
