# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0008_auto_20180808_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
